### ISSUE TITLE
resolution changing 

### ISSUE THREAD

**Issue by Pmcnaught** [tribalfs/PixelsPub#173]
Thanks for your App, I use it alot. I have a galaxy tab active 3 but have found the issue on other Samsung devices.

I find when I reduce the width I cannot also reduce the height of the displayed area, even when default aspect ratio is disabled.

I would really like to have more flexibility in this way. Do you have any suggestions?

Peter

**Comment by Abrilmm** [comment]
No entiendo como usar la aplicación

**Comment by tribalfs** [comment]
Provide complete details.
